services:
  messages:
    image: cantanope/message_machine:latest
    container_name: message_machine_container
    ports:
      - "8003:80"
    volumes:
      - ./app:/app
    restart: unless-stopped
    networks:
      - default